version: '3.8'

services:
  nerd-backup:
    image: nerd-backup:latest # Make sure to build your Docker image first: docker build -t nerd-backup .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    environment:
      - NERD_BACKUP_RESTIC_REPOSITORY=<your_restic_repository_path>
      - NERD_BACKUP_RESTIC_PASSWORD=<your_restic_password>
      - NERD_BACKUP_AWS_ACCESS_KEY_ID=<your_aws_access_key_id>
      - NERD_BACKUP_AWS_SECRET_ACCESS_KEY=<your_aws_secret_access_key>
      - NERD_BACKUP_VOLUMES_TO_BACKUP=<volume1,volume2,volume3>
      - NERD_BACKUP_TAG_PREFIX=<your_tag_prefix>
    # Set restart to "no" for one-off job behavior
    restart: "no"
    # Use command to override the entrypoint if needed, or rely on ENTRYPOINT from Dockerfile
    # command: ./nerd-backup 
