name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'Optional: Docker image tag (e.g., v1.0.0). If not provided, will use current date.'
        required: false
        type: string

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow checkout
      packages: write # Allow publishing to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ inputs.tag || steps.get_date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
